#### general settings
name: CMOS_Cityscapes_BSR
use_tb_logger: true
scale: 4
gpu_ids: [0]
kernel_size: 61
n_classes: 19
val_blur: true
val_seg: true
val_sr: false

#### datasets
datasets:
  train:
    name: Cityscapes-BSR
    dataroot_GT: ../datasets/Cityscapes-BSR/train/GT
    dataroot_LR: ../datasets/Cityscapes-BSR/train/LRx4
    dataroot_blur: ../datasets/Cityscapes-BSR/train/blur
    dataroot_seg: ../datasets/Cityscapes-BSR/train/semseg

    use_shuffle: true
    n_workers: 8
    batch_size: 8
    GT_size: [480, 640]
    LR_size: [120, 160]
    use_flip: true
    use_rot: false
    use_scale: true
  val:
    name: Cityscapes-BSR-val
    dataroot_GT: ../datasets/Cityscapes-BSR/val/GT
    dataroot_LR: ../datasets/Cityscapes-BSR/val/LRx4
    dataroot_blur: ../datasets/Cityscapes-BSR/val/blur
    dataroot_seg: ../datasets/Cityscapes-BSR/val/semseg


#### network structures
network_G:
  which_model_G: CMOS
  in_nc: 3
  out_nc: ~
  nf: ~
  nb: ~
  gc: ~


#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~


#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  nepoch: 700
  warmup_iter: 3720 # 372 iterations per epoch
  T_period: [148800, 148800]
  restarts: [148800]
  restart_weights: [1.0]
  eta_min: !!float 1e-7

  cmos_criterion: cmos
  cmos_weight: [0.5, 0.5, 1.0, 1.0]

  manual_seed: 0
  val_freq: !!float 5e3


#### logger
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
